name: Deploy to server

on: push # It is possible to put directly

jobs: 
    first_jobs:
        runs-on: ubuntu-latest

        steps:
            - run: echo "First job in the same yaml"

    second_jobs:
        runs-on: ubuntu-latest

        steps:
            - run: echo "Second job in the same yaml"