name: Deploy to server

on: push # It is possible to put directly

jobs: 
    first_jobs:
        runs-on: ubuntu-latest

        steps:
            - run: echo "First job in the same yaml"

    second_jobs:
        runs-on: ubuntu-latest

        steps:
            - run: echo "Second job in the same yaml"

    third_jobs:
        needs: [first_jobs, second_jobs] # Run this job after running the second_job
        runs-on: ubuntu-latest

        steps:
            - run: echo "Third job in the same yaml with dependencies"