name: "Deploy CodigoFacilito"

# trigger
on: 
  push:
    branches: ["master"]  # Cuando se haga un push sobre la rama main, ejecute este wokrkflow

jobs:
  deploy-codigofacilito:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4   # Download code in the virtual machine
      - run: echo "Pull of code"
      - run: echo "Run migrations"
      - run: echo "Generaate binary"
      - run: echo "Publish version"
  # send-notificacion:
  # test-code: 